services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: productvisualizer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: productvisualizer
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - productvisualizer-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: productvisualizer-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://appuser:apppassword@mongodb:27017/productvisualizer?authSource=productvisualizer
      - JWT_SECRET=dev-secret-key-change-in-production
      - CORS_ORIGIN=http://localhost:8000
      - API_BASE_URL=http://localhost:3000/api
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - productvisualizer-network
    command: npm run dev

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: productvisualizer-frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=http://localhost:3000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - productvisualizer-network
    command: python3 -m http.server 8000

volumes:
  mongodb_data:
    driver: local

networks:
  productvisualizer-network:
    driver: bridge 